---
title: "Rapport d'analyse - projet informatique"
format: pdf
editor: visual
---


# Introduction

# Diagramme d'architecture

```{r}

```


# Diagrammes d'activité 

## Administrateur

```{r}

```

## Client

```{r}

```

## Collaborateur

```{r}

```


# Diagramme de Gantt
```{mermaid}
gantt
    todayMarker off
    dateFormat DD-MM-YYYY
    axisFormat %d-%m
    title Diagramme de Gantt
    section Analyse du sujet
        Choix des foncionnalités : done, 26-08-2026, 17-09-2026
        Diagrammes : done, 04-09-2026, 13d
        Rédaction : done, 11-09-2026, 6d
        Rédaction : 13-11-2026, 21-11-2026
        Diaporama : 22-11-2026, 09-12-2026

    section Développement
        Classes : 18-09-2026, 1w
        Tests : 22-09-2026, 1w
        BDD + DAO : 29-09-2026, 09-10-2026
        Tests : 06-10-2026, 1w
        Service API : 13-10-2026, 23-10-2026
        Tests : 20-10-2026, 1w
        Fonctionnalités : 27-10-2026, 13-11-2026
        Tests : 03-11-2026, 10d
        Autres options : 13-11-2026, 21-11-2026
        Tests : 17-11-2026, 21-11-2026

    section Échéances
        Dossier d'analyse : milestone, crit, 17-09-2026, 20h
        Rapport final : milestone, crit, 21-11-2026, 20h
        Soutenance : milestone, crit, 09-12-2026, 1d

```


